name: CI

on:
    push:
        branches: ["main", "dev"]
    pull_request:
        branches: ["main", "dev"]

jobs:
    Typos:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Actions Repository
              uses: actions/checkout@v4
            - name: Install uv
              uses: astral-sh/setup-uv@v6
            - name: Install gdtoolkit
              run: uv pip install "gdtoolkit==4.*"
            - name: Check Fmt
              run: uv run gdformat -c src
